### PR TITLE
Neg fallout - 2

### PR DESCRIPTION
**Pull request by kvark**

### CODE REVIEW

**Comment by va1erian** [comment]
Hey, thanks for the quick fix. However, it seems that your commit does not build with Rust 1.0.0-beta, at least on Windows 64. It works fine with the latest available nightly (083b8a404 2015-04-05)

```
   Compiling cgmath v0.1.3 (https://github.com/kvark/cgmath-rs.git?branch=neg2#498df017)
[...]\neg2\src\transform.rs:240:24: 240:25 error: parameter `S` is never used
[...]\neg2\src\transform.rs:240 pub trait ToComponents<S, V: Vector<S>, P: Point<S, V>, R: Rotation<S, V, P>> {
                                                                                                                  ^
[...]\neg2\src\transform.rs:240:25: 240:25 help: consider removing `S` or using a marker such as `core::marker::PhantomFn`
[...]\neg2\src\transform.rs:240:41: 240:42 error: parameter `P` is never used
[...]\neg2\src\transform.rs:240 pub trait ToComponents<S, V: Vector<S>, P: Point<S, V>, R: Rotation<S, V, P>> {
                                                                                                                                   ^
[...]\neg2\src\transform.rs:240:42: 240:42 help: consider removing `P` or using a marker such as `core::marker::PhantomFn`
error: aborting due to 2 previous errors
Could not compile `cgmath`.
```

**Comment by kvark** [comment]
@va1erian We need a 1.0 branch here, either taken before my PR or after merging it (depending on what path is simpler, to me it looks like the latter). The master should continue following rust nightly, and that's what my PR is about.

**Comment by kvark** [comment]
@bjz ping

**Comment by kvark** [comment]
Ok, waiting gets boring rather quickly. Merging.

**Pull request merged**
