### PR TITLE
Remove FixedArray trait in favour of std::convert

### LINKED ISSUE #225: ToX -> Into<X>
Instead of the ToX traits, did you consider implementing From<X> ?

### PR DESCRIPTION
**Pull request by bjz**
Fixes #225
Closes #222

This is a breaking change and will probably require a version bump. I would like to do other things before this happens though, like removing all the operator methods in favor of implementing the operator traits.

### CODE REVIEW

**Comment by tomaka** [comment]
:+1:

**Comment by bjz** [comment]
Hmm - dunno why travis is not working on this.

**Comment by tomaka** [comment]
Travis currently has some problems: https://www.traviscistatus.com/

**Comment by csherratt** [comment]
:o This is pretty amazing @bjz.

**Comment by kvark** [comment]
Hey @bjz ! Glad to see you back at the front lines ;)

**Pull request merged**
